### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by sprain** [opichon/UAMPostmarkSwiftMailerBundle#1]
I get this error when trying to install your bundle:

```
Problem 1
    - Installation request for uam/postmark-swiftmailer-bundle 0.1.*@dev -> satisfiable by uam/postmark-swiftmailer-bundle[0.1.x-dev].
    - uam/postmark-swiftmailer-bundle 0.1.x-dev requires mlpz/postmark-bundle dev-master -> no matching package found.
```

**Comment by opichon** [comment]
You need to do 1 of these things:
- include "mlpz/postmark-bundle": "dev-master" in your project's composer.json
- change the minimum stability of your project to "dev"

**Comment by opichon** [comment]
I've updated the bundle's composer.json. You can now install it directly without having to set your minimum stability to "dev' or having to declare the mlpz/postmark-bundle.
