### ISSUE TITLE
InvalidArgumentException: The service definition "swiftmailer.mailer.transport.uam_postmark" does not exist.

### ISSUE THREAD

**Issue by zuzuleinen** [opichon/UAMPostmarkSwiftMailerBundle#2]
I installed the bundle following all the instruction, but for some reason I get this exception when I go to my project:
InvalidArgumentException: The service definition "swiftmailer.mailer.transport.uam_postmark" does not exist.

This is my configuration for swiftmailer:

``` yaml
swiftmailer:
    transport: uam_postmark
```

**Comment by opichon** [comment]
I've put in a fix. Also added a test command. Please update your app.

**Comment by zuzuleinen** [comment]
Thanks a lot!
